/* Интерактивы выполняются локально в браузере. Внешние модели не вызываются. */
(function(){
  "use strict";
  var lastFocus=null;
  function initImages(){document.querySelectorAll('.slide-image').forEach(function(b){var img=b.querySelector('img'),fallback=b.querySelector('.slide-fallback');function failed(){img.hidden=true;img.style.display='none';b.disabled=true;b.style.cursor='default';fallback.hidden=false;b.removeAttribute('data-lightbox-src')}function loaded(){if(img.naturalWidth){fallback.hidden=true;fallback.style.display='none'}}img.addEventListener('error',failed);img.addEventListener('load',loaded);if(img.complete){if(img.naturalWidth)loaded();else failed()}})}
  function copy(text,button){
    var done=function(){var old=button.textContent;button.textContent="Скопировано";setTimeout(function(){button.textContent=old},1200)};
    if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(text).then(done).catch(function(){fallbackCopy(text,done)})}else{fallbackCopy(text,done)}
  }
  function fallbackCopy(text,done){var x=document.createElement("textarea");x.value=text;x.style.position="fixed";x.style.opacity="0";document.body.appendChild(x);x.select();try{if(document.execCommand("copy"))done()}catch(e){}x.remove()}
  function initCopy(){document.querySelectorAll("[data-copy-target]").forEach(function(b){b.addEventListener("click",function(){var t=document.getElementById(b.dataset.copyTarget);if(t)copy(t.value||t.innerText,b)})})}
  function initTeacher(){var b=document.getElementById("teacherToggle");if(!b)return;var on=false;try{on=localStorage.getItem("dpo14-revision2-teacher")==="1"}catch(e){}function paint(){document.body.classList.toggle("teacher-mode",on);document.querySelectorAll('.teacher-note').forEach(function(n){n.open=on});b.setAttribute("aria-pressed",String(on));b.textContent=on?"Скрыть заметки":"Режим преподавателя"}b.addEventListener("click",function(){on=!on;try{localStorage.setItem("dpo14-revision2-teacher",on?"1":"0")}catch(e){}paint()});paint()}
  function initProgress(){var bar=document.getElementById("progressLine");var links=[].slice.call(document.querySelectorAll("[data-nav]"));function scroll(){var max=document.documentElement.scrollHeight-innerHeight;bar.style.width=(max?scrollY/max*100:0)+"%"}addEventListener("scroll",scroll,{passive:true});scroll();if(!("IntersectionObserver" in window))return;var io=new IntersectionObserver(function(es){es.forEach(function(e){if(!e.isIntersecting)return;links.forEach(function(a){a.classList.toggle("active",a.dataset.nav===e.target.id)})})},{rootMargin:"-30% 0px -55%",threshold:0});document.querySelectorAll("main section[data-section]").forEach(function(x){io.observe(x)})}
  function initLightbox(){var box=document.getElementById("lightbox"),image=document.getElementById("lightboxImage");if(!box||!image)return;function close(){box.classList.remove("open");box.setAttribute("aria-hidden","true");image.removeAttribute("src");if(lastFocus)lastFocus.focus();lastFocus=null}document.querySelectorAll("[data-lightbox-src]").forEach(function(b){b.addEventListener("click",function(){lastFocus=b;image.src=b.dataset.lightboxSrc;image.alt=b.dataset.lightboxAlt;box.classList.add("open");box.setAttribute("aria-hidden","false");box.querySelector("button").focus()})});box.querySelector(".lightbox-close").addEventListener("click",close);box.addEventListener("click",function(e){if(e.target===box)close()});document.addEventListener("keydown",function(e){if(e.key==="Escape"&&box.classList.contains("open"))close();if(e.key==="Tab"&&box.classList.contains("open")){e.preventDefault();box.querySelector("button").focus()}})}
  function initClaims(root){var cards=[].slice.call(root.querySelectorAll(".claim-card")),out=root.querySelector(".feedback");function reset(){cards.forEach(function(c){c.classList.remove("ok","bad");c.querySelector("select").value="";c.querySelector(".claim-feedback").textContent=""});out.textContent="Сначала выберите статус каждого утверждения после проверки его основания.";out.className="feedback"}root.querySelector("[data-claims-check]").addEventListener("click",function(){var score=0;cards.forEach(function(c){var v=c.querySelector("select").value,good=c.dataset.correct;c.classList.toggle("ok",v===good);c.classList.toggle("bad",!!v&&v!==good);c.querySelector(".claim-feedback").textContent=!v?"Статус не выбран.":v===good?"Статус соответствует учебному разбору.":"Сверьте статус с основанием, датой и контекстом.";if(v===good)score++});out.textContent="Совпало "+score+" из "+cards.length+". Это учебный разбор: для рабочего решения всё равно нужен первичный источник и ответственный.";out.className="feedback "+(score===cards.length?"ok":"bad")});root.querySelector("[data-interactive-reset]").addEventListener("click",reset);reset()}
  function initBias(root){var out=root.querySelector('.feedback'),answer=root.querySelector('[data-bias-answer]'),profiles=root.querySelector('.bias-profiles');root.querySelector('[data-bias-compare]').addEventListener('click',function(){var good=answer.value==='age';out.textContent=!answer.value?'Сначала выберите, для какого вывода нет данных.':good?'Верно: скорость обучения не измерялась, а возраст не входит в рубрику. Исправленный эталон: А — 2+2+1=5; Б — 2+2+1=5. Это разбор учебной ошибки, не оценка устойчивой предвзятости какой-либо модели.':'Проверьте исходные профили: опыт, тест и график одинаковы. Различается возраст, но он не входит в рубрику и не доказывает скорость обучения.';out.className='feedback '+(good?'ok':'bad')});root.querySelector('[data-bias-swap]').addEventListener('click',function(){profiles.appendChild(profiles.firstElementChild);out.textContent='Порядок карточек изменён, факты и рубрика — нет. Эталон остаётся 5 и 5. При повторном запросе модели сравните основания оценки, а не порядок вывода.';out.className='feedback'});root.querySelector('[data-interactive-reset]').addEventListener('click',function(){answer.value='';profiles.insertBefore(profiles.querySelector('[data-profile="A"]'),profiles.firstElementChild);out.textContent='Сначала посчитайте по рубрике, затем найдите лишний вывод.';out.className='feedback'})}
  function initDeepfake(root){var out=root.querySelector(".feedback"),step=0,ok={stop:"Верно: передача остановлена. Теперь выберите независимый канал подтверждения.",known:"Верно: поручение подтверждено известным контактом. Отдельно проверьте адресата.",recipient:"Верно: личность, адресат и полномочия проверены раздельно. Можно действовать только по порядку."},bad={"wrong-send":"Небезопасно: знакомый голос не подтверждает полномочия и адресата.","wrong-chat":"Небезопасно: тот же чат не является независимым каналом.","wrong-number":"Небезопасно: номер из сообщения может контролировать тот же отправитель.","wrong-address":"Небезопасно: подтверждение личности не разрешает передачу новому адресату без проверки."};function show(){root.querySelectorAll('[data-deepfake-step]').forEach(function(x){x.hidden=Number(x.dataset.deepfakeStep)!==step})}root.querySelectorAll("[data-deepfake-choice]").forEach(function(b){b.addEventListener("click",function(){var k=b.dataset.deepfakeChoice;if(bad[k]){out.textContent=bad[k];out.className="feedback bad";return}var need={stop:0,known:1,recipient:2}[k];if(need!==step)return;step++;b.classList.add("done");out.textContent=ok[k];out.className="feedback ok";show()})});root.querySelector("[data-interactive-reset]").addEventListener("click",function(){step=0;root.querySelectorAll(".choice-stack button").forEach(function(x){x.classList.remove("done")});out.textContent="Выберите первое действие.";out.className="feedback";show()});show()}
  function reset(root){var out=root.querySelector(".feedback");root.querySelectorAll("input").forEach(function(x){x.checked=false});root.querySelectorAll("select").forEach(function(x){x.value=""});if(out){out.textContent="Выберите действие и нажмите «Проверить».";out.className="feedback"}}
  function initRoute(root){var out=root.querySelector('.feedback'),step=0,items=root.querySelectorAll('.route-gates li'),next=root.querySelector('[data-route="next"]'),unknown=root.querySelector('[data-route="unknown"]'),known=root.querySelector('[data-route="known"]');var messages=['','1. Цель: нужен пустой шаблон ответа на заявку. Реальный реестр техники для него не нужен.','2. Минимум: опишите условный симптом. Не добавляйте контакты и сетевые адреса.','3. Категория: если неизвестна, остановитесь и уточните. Выберите ветку ниже.','4. Контур: проверьте разрешённую среду. Известная категория сама по себе не разрешает внешний сервис.','5. Подготовка: создайте минимальную копию, проверьте скрытые слои и остаточный риск.','6. Контроль входа завершён только после проверки фактического файла и разрешения на передачу. После ответа предстоит отдельная проверка результата.'];function paint(){items.forEach(function(x,i){x.classList.toggle('active',i===step-1);if(i===step-1)x.setAttribute('aria-current','step');else x.removeAttribute('aria-current')});next.disabled=step===0||step===3||step===6;unknown.hidden=known.hidden=step!==3;out.textContent=messages[step]||'Начните с определения результата, а не с загрузки файла.';out.className='feedback'}root.querySelectorAll('[data-route]').forEach(function(b){b.addEventListener('click',function(){var k=b.dataset.route;if(k==='start')step=1;if(k==='next'&&step>0&&step<6&&step!==3)step++;if(k==='known'&&step===3)step=4;paint();if(k==='unknown'&&step===3){out.textContent='СТОП: категория неизвестна. Ничего не передаём, уточняем у ответственного. Только после уточнения можно продолжить учебный маршрут.';out.className='feedback bad'}})});root.querySelector('[data-interactive-reset]').addEventListener('click',function(){step=0;paint()});paint()}
  function initMinimize(root){var out=root.querySelector('.feedback');root.querySelector('[data-minimize-check]').addEventListener('click',function(){var values=[].slice.call(root.querySelectorAll('input:checked')).map(function(x){return x.value});var needed=['goal','delay'];var extra=values.filter(function(v){return needed.indexOf(v)===-1});var missing=needed.filter(function(v){return values.indexOf(v)===-1});var ok=!extra.length&&!missing.length;if(ok){out.textContent='Верно: цель письма и факт задержки достаточны. В учебном черновике поставщик и договор остаются метками [ПОСТАВЩИК] и [ДОГОВОР].';out.className='feedback ok';return}var why={name:'ФИО не меняет содержание запроса о сроке.',contact:'Личный контакт не нужен для учебного черновика и не должен передаваться без цели.',amount:'Стоимость договора не нужна: здесь не рассчитывается неустойка.',contract:'Реальный номер договора заменяем меткой [ДОГОВОР] в учебном примере.'};var notes=[];if(missing.length)notes.push('Не хватает: '+missing.map(function(v){return v==='goal'?'цели письма':'факта задержки 5 дней'}).join(' и ')+'.');extra.forEach(function(v){notes.push(why[v])});out.textContent=notes.join(' ');out.className='feedback bad'})}
  function initRights(root){var out=root.querySelector('.feedback');root.querySelector('[data-rights-check]').addEventListener('click',function(){var a=root.querySelector('[data-rights-source]').value,b=root.querySelector('[data-rights-terms]').value,c=root.querySelector('[data-rights-credit]').value;if(!a||!b||!c){out.textContent='Выберите все три условия.';out.className='feedback bad';return}var ok=(a==='own'||a==='licensed')&&b==='yes'&&c==='done';out.textContent=ok?'Есть учебное основание продолжить. Сохраните источник и условия использования.':'Публикацию нужно остановить: замените материал или уточните лицензию и требуемую атрибуцию.';out.className='feedback '+(ok?'ok':'bad')})}
  function initInteractive(){document.querySelectorAll(".interactive").forEach(function(root){var type=root.dataset.interactiveType;if(type==="claims")initClaims(root);if(type==="bias")initBias(root);if(type==="deepfake")initDeepfake(root);if(type==="route")initRoute(root);if(type==="minimize")initMinimize(root);if(type==="rights")initRights(root);if(type==='minimize'||type==='rights')root.querySelector('[data-interactive-reset]').addEventListener('click',function(){reset(root)})})}
  document.addEventListener("DOMContentLoaded",function(){initImages();initCopy();initTeacher();initProgress();initLightbox();initInteractive()});
})();
